version: "3.1"
services:
    php80:
        image: webdevops/php-dev:8.0
        container_name: rest-php80
        working_dir: /app
        env_file:
            - ./.env
        volumes:
            - ..:/app
    php81:
        image: webdevops/php-dev:8.1
        container_name: rest-php81
        working_dir: /app
        env_file:
            - ./.env
        volumes:
            - ..:/app
