name: Pull Request
on:
  push:
    branches:
      - 0.x
  pull_request: ~
jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php8.0-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php8.0-
      - name: Install dependencies
        run: composer update --no-interaction --no-progress --prefer-stable
      - name: Run php cs fixer
        run: vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php8.0-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php8.0-
      - name: Install dependencies
        run: composer update --no-interaction --no-progress --prefer-stable
      - name: Run psalm
        run: vendor/bin/psalm --no-cache --show-info=true --shepherd
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: 8.0
            composer-flags: "--prefer-stable"
            symfony-require: "5.4.*"
          - php-version: 8.0
            composer-flags: "--prefer-stable"
            symfony-require: ""
          - php-version: 8.1
            composer-flags: "--ignore-platform-req=php"
            symfony-require: ""
    steps:
      - uses: actions/checkout@v1
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php-version }}-symfony${{ matrix.symfony-require }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php-version }}-symfony${{ matrix.symfony-require }}-
      - name: Install dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-require }}
        run: |
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
          composer update --no-interaction --no-progress ${{ matrix.composer-flags }}
      - name: Run testsuites
        run: vendor/bin/phpunit --configuration=phpunit.xml.dist --coverage-clover=coverage.xml
      - name: Send code coverage report to Codecov.io
        if: matrix.php-version == '8.1'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOVIO_TOKEN }}
        run: bash <(curl -s https://codecov.io/bash)
      - name: Run infection
        if: matrix.php-version == '8.1'
        env:
          INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
        run: vendor/bin/infection
